id: PD2B503B2
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA3JT13311
  instance_id: http://purl.bdrc.io/resource/IE3JT13311
  collection_id: http://purl.bdrc.io/resource/PR0ET001
  language_id: None
  title:
    bo:
    - སོ་སོ་ཐར་པའི་མདོའི་འགྲེལ་པ་རིན་ཆེན་འབྱུང་གནས།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P385
  publisher: DharmaDownload
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    ea1180c79c4e45dabed030e75ebe9255:
      title: ༄༅།་།སོ་སོ་ཐར་པའི་མདོའི་འགྲེལ་པ་རིན་ཆེན་འབྱུང་གནས་ཞེས་བྱ་བ་བཞུགས་སོ།་།
      volume_number: 1
      base_file: UT3JT13311_001_0000.txt
      reference: http://purl.bdrc.io/resource/VL5B209E3B493ACC0C
      image_group: null
      quality: null
  reproductionOf: []
created_at: '2021-12-22T11:19:53.069584'
last_modified_at: '2021-12-22T11:19:53.069591'
statistics:
  total_words: 34824
  total_non_words: 4553
quality:
  non_words_ratio: 0.13
